### ISSUE TITLE
secp256k1_ec_pubkey_decompress causes Segmentation Fault

### ISSUE THREAD

**Issue by rubensayshi** [afk11/secp256k1-php#5]
- doesn't seem to happen all the time
 - seems to have something to do with being the only ZVAL we modify by reference

`php -dextension=secp256k1.so vendor/phpunit/phpunit/phpunit tests/Secp256k1PubkeyDecompressTest.php` to reproduce

**Comment by afk11** [comment]
Yeah I've had times where it actually makes it past the tests.. It seems to be the main thing holding up the test suite at the moment. 

I've had pot luck with most of them, but this one just won't go away.

**Comment by rubensayshi** [comment]
fixed
